title: "Scala IDE for Eclipse"
keywords:
- Scala
- IDE
- Eclipse
- Scala Programming Language
- ScalaIDE
- ScalaIDE Download

permalink: /:categories/:title.html
baseurl: "http://scala-ide.org"

markdown: kramdown
regenerate: true

